# This is the network config written by 'subiquity'
network:
  ethernets:
    ens160:
      dhcp4: false
      addresses: [10.0.6.11/24]
      gateway4: 10.0.6.1
      nameservers:
        addresses: [10.0.6.1,10.0.6.2,10.0.6.3]
  version: 2
